CREATE TABLE Veiculo (
IDVeiculo INTEGER PRIMARY KEY,
Modelo VARCHAR2(50) NOT NULL,
Placa VARCHAR2(7) UNIQUE NOT NULL,
AnoFabricacao INTEGER NOT NULL,
TipoCombustivel VARCHAR2(20) NOT NULL,
CapacidadeCarga INTEGER
);
 
CREATE TABLE Motorista (
IDMotoista INTEGER PRIMARY KEY,
Nome VARCHAR2(100) NOT NULL,
CPF VARCHAR2(11) UNIQUE NOT NULL,
CNH VARCHAR2(11) UNIQUE NOT NULL,
Telefone VARCHAR2(20),
Email VARCHAR2(100)
);
 
CREATE TABLE Manutencao (
IDManutencao INTEGER PRIMARY KEY,
Data DATE NOT NULL,
TipoServico VARCHAR2(100) NOT NULL,
PecasSubstituidas VARCHAR2(200),
ValorGasto NUMBER(10,2) NOT NULL,
IDVeiculo INTEGER NOT NULL,
FOREIGN KEY (IDVeiculo) REFERENCES Veiculo(IDVeiculo)
);
 
CREATE TABLE Abastecimento (
IDAbastecimento INTEGER PRIMARY KEY,
Data DATE NOT NULL,
TipoCombustivel VARCHAR2(20) NOT NULL,
QuantidadeAbastecida NUMBER(10,2) NOT NULL,
ValorGasto NUMBER(10,2) NOT NULL,
IDVeiculo INTEGER NOT NULL,
FOREIGN KEY (IDVeiculo) REFERENCES Veiculo(IDVeiculo)
);
 
CREATE TABLE Despesa (
IDDespesa INTEGER PRIMARY KEY,
Descricao VARCHAR2(200) NOT NULL,
Valor NUMBER(10,2) NOT NULL,
DataVencimento DATE NOT NULL,
IDVeiculo INTEGER NOT NULL,
TipoDespesa VARCHAR2(50) NOT NULL,
FOREIGN KEY (IDVeiculo) REFERENCES Veiculo(IDVeiculo)
);
 
CREATE TABLE VeiculoMotorista (
IDVeiculo INTEGER NOT NULL,
IDMotoista INTEGER NOT NULL,
PRIMARY KEY (IDVeiculo, IDMotoista),
FOREIGN KEY (IDVeiculo) REFERENCES Veiculo(IDVeiculo),
FOREIGN KEY (IDMotoista) REFERENCES Motorista(IDMotoista)
);
